name: iOS starter workflow

on: 
  push:
    branches:
      - 4.[0-9]+.[0-9]+-alpha
      - 4.[0-9]+.[0-9]+-alpha-[A-Za-z0-9]+
      - 4.[0-9]+.[0-9]+-beta
      - 4.[0-9]+.[0-9]+-beta-[A-Za-z0-9]+
      - 4.[0-9]+.[0-9]+

jobs:
  job_publish:
    name: publish
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # 暂时屏蔽 会卡在这一步骤
      # - name: Cache .cocoapods
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cocoapods
      #     key: ${{ runner.os }}-cocoapods
      #     restore-keys: ${{ runner.os }}-cocoapods

      - name: init oss
        run: |
          echo "[Credentials]" > ~/.ossutilconfig
          echo "language=CH" >> ~/.ossutilconfig
          echo "endpoint=${{ secrets.OSS_ENDPOINT }}" >> ~/.ossutilconfig
          echo "accessKeyID=${{ secrets.OSS_ACCESS_KEY_ID }}" >> ~/.ossutilconfig
          echo "accessKeySecret=${{ secrets.OSS_ACCESS_KEY_SECRET }}" >> ~/.ossutilconfig
          curl -o ./Yodo1MasSdk/ossutilmac64 http://gosspublic.alicdn.com/ossutil/1.7.3/ossutilmac64
          chmod 755 ./Yodo1MasSdk/ossutilmac64

      - name: chmod publish
        run: |
          chmod 755 ./Yodo1MasSdk/publish.sh
          chmod 755 ./Yodo1MasSdk/publish.sh

      - name: publish
        run: sh Yodo1MasSdk/publish.sh Pre ${{ secrets.TOKEN }} ${{ secrets.TING_TOKEN }}